#!/bin/bash
# Run tldr + circle stages for batch_000 to batch_004
# Stages 1-5 already complete for these batches

mkdir -p /groups/rubin/projects/kuang/out/IS_cycle/logs

sbatch --job-name=batch_000_tc --partition=standard --qos=standard --cpus-per-task=48 --mem=192G --time=4-00:00:00 --output=/groups/rubin/projects/kuang/out/IS_cycle/logs/batch_000_tc_%j.log --error=/groups/rubin/projects/kuang/out/IS_cycle/logs/batch_000_tc_%j.log --wrap "conda run -n opfi python /home/kuangh/tools/Cycle/scripts/run_pipeline.py --metadata /home/kuangh/tools/Cycle/data/batches/batch_000.tsv --outdir /groups/rubin/projects/kuang/out/IS_cycle/batch_000 --threads 8 --sort-memory 4G --steps tldr circle --tldr-parallel 6 --tldr-procs 8"
sbatch --job-name=batch_001_tc --partition=standard --qos=standard --cpus-per-task=48 --mem=192G --time=4-00:00:00 --output=/groups/rubin/projects/kuang/out/IS_cycle/logs/batch_001_tc_%j.log --error=/groups/rubin/projects/kuang/out/IS_cycle/logs/batch_001_tc_%j.log --wrap "conda run -n opfi python /home/kuangh/tools/Cycle/scripts/run_pipeline.py --metadata /home/kuangh/tools/Cycle/data/batches/batch_001.tsv --outdir /groups/rubin/projects/kuang/out/IS_cycle/batch_001 --threads 8 --sort-memory 4G --steps tldr circle --tldr-parallel 6 --tldr-procs 8"
sbatch --job-name=batch_002_tc --partition=standard --qos=standard --cpus-per-task=48 --mem=192G --time=4-00:00:00 --output=/groups/rubin/projects/kuang/out/IS_cycle/logs/batch_002_tc_%j.log --error=/groups/rubin/projects/kuang/out/IS_cycle/logs/batch_002_tc_%j.log --wrap "conda run -n opfi python /home/kuangh/tools/Cycle/scripts/run_pipeline.py --metadata /home/kuangh/tools/Cycle/data/batches/batch_002.tsv --outdir /groups/rubin/projects/kuang/out/IS_cycle/batch_002 --threads 8 --sort-memory 4G --steps tldr circle --tldr-parallel 6 --tldr-procs 8"
sbatch --job-name=batch_003_tc --partition=standard --qos=standard --cpus-per-task=48 --mem=192G --time=4-00:00:00 --output=/groups/rubin/projects/kuang/out/IS_cycle/logs/batch_003_tc_%j.log --error=/groups/rubin/projects/kuang/out/IS_cycle/logs/batch_003_tc_%j.log --wrap "conda run -n opfi python /home/kuangh/tools/Cycle/scripts/run_pipeline.py --metadata /home/kuangh/tools/Cycle/data/batches/batch_003.tsv --outdir /groups/rubin/projects/kuang/out/IS_cycle/batch_003 --threads 8 --sort-memory 4G --steps tldr circle --tldr-parallel 6 --tldr-procs 8"
sbatch --job-name=batch_004_tc --partition=standard --qos=standard --cpus-per-task=48 --mem=192G --time=4-00:00:00 --output=/groups/rubin/projects/kuang/out/IS_cycle/logs/batch_004_tc_%j.log --error=/groups/rubin/projects/kuang/out/IS_cycle/logs/batch_004_tc_%j.log --wrap "conda run -n opfi python /home/kuangh/tools/Cycle/scripts/run_pipeline.py --metadata /home/kuangh/tools/Cycle/data/batches/batch_004.tsv --outdir /groups/rubin/projects/kuang/out/IS_cycle/batch_004 --threads 8 --sort-memory 4G --steps tldr circle --tldr-parallel 6 --tldr-procs 8"
